### ISSUE TITLE
Support meetings that don't respect the usual slots

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#100]
The AC meeting during TPAC may start and stop at times that are slightly different from the usual slots. To be able to include the AC meeting in the system, we need to be more flexible on actual start/end times, while making sure that the calendar entry has the right information.

**Comment by ianbjacobs** [comment]
One idea is to support a syntax for specifying "post-aggregation" calendar adjustments. There are three scenarios:

* Starting a bit before the first slot of the day (e.g., 8:30 start instead of 9:00).
* Starting slightly after or ending slightly before the bounds of a defined slot.
* Ending slightly after the last slot of the day (e.g., 18:30 end time instead of 18:00).

Here are some ways to address the above scenarios (adjust syntax to taste):

* 09:00<08:30>
* 09:00-10:30<10:00>
* Monday, 09:30; Monday, 11:30<11:00>
* Thursday, 09:30<10:00>; Thursday, 11:30; Thursday, 14:30; Thursday, 17:00<16:00>

Note:

* It should trigger an error if there is a calendar adjustment for an earlier start time specified on a slot that is not the first slot of the day. In this case, because the group needs the room and others might also need it, the group should include the first slot and specify a "later start" calendar adjustment. 
* Same thing if there is a calendar adjustment for a later end time specified on a slot that is not the last slot of the day.

**Comment by ianbjacobs** [comment]
Wow!!
