### ISSUE TITLE
For group meetings, support group name + highlight in title

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#137]
Use case: A group wants the calendar / grid to display something like "WICG: Digital Credentials API" in order to attract participants.

Idea (discussed in email):

* Syntax of title:  <code>&lt;group_name&gt; ":" | ">" &lt;highlight&gt;</code>
* By having two separator options, we account for situations where the &lt;highlight&gt; includes, for example, ":".
* The scheduler will treat this as its own meeting with its own slot, with the full title.
* The calendar will consider it part of the <group> calendar. However, because the title is not merely the title of the group, it should have its own entry in the calendar. Thus, for example:

<pre>
  09:00-10:30: Web Platform Incubator CG
  11:00-12:30: WICG: Digital Credentials API
  14:00-16:00: Web Platform Incubator CG
</pre>

**Comment by ianbjacobs** [comment]
I think you pointed out that the code that converts titles to group names currently assumes that if it doesn't recognize a group name, it will assume the name is correct and defer to validation to detect the error. That makes it more difficult to distinguish an intentional highlight from a group name with a typo.

What if we instead add a field to the meeting session template to allow an optional highlight title (default: null). The following code would have to be updated:
 * Generation of event titles for calendar
 * Generation of session names in generated HTML

The title is also used to generate short names, but I'm not sure if that's used for meetings.

**Comment by tidoust** [comment]
> I think you pointed out that the code that converts titles to group names currently assumes that if it doesn't recognize a group name, it will assume the name is correct and defer to validation to detect the error. That makes it more difficult to distinguish an intentional highlight from a group name with a typo.

That's right, but I was making that point as part of a discussion on whether we could get rid of token separators (`,`, `&`, `and`, `:`, `>`) entirely. We could in theory, but if we do, we end up with the problem you mention. As long as we keep token separators, there shouldn't be any problem.

> What if we instead add a field to the meeting session template to allow an optional highlight title (default: null). 

We would end up with a list of open issues (in the repo, in the project), some of which appearing to be duplicates as in your example. That looks like a bug because the highlight won't appear at the listing level. We'll be naturally tempted to *fix* these duplicates, even though there's nothing to fix. That's similar to how the two unmerged "Audio WG" lines in the grid looked like a bug yesterday when we prepared TPAC pages because the room names did not appear.

If we start putting highlight information in the issue description, ideally, we'd find a mechanism that allows us to get back to one and only one issue per group. On top of my head, I don't see a reasonably simple way to do that though, so propose to stick to highlights in the title instead.

**Comment by ianbjacobs** [comment]
Sounds good.

**Comment by tidoust** [comment]
Should be done. I also added a [bit of documentation](https://github.com/w3c/tpac-breakouts/wiki/For-TPAC-Meeting-Planners#group-meeting-highlight) to the wiki page.

**Comment by ianbjacobs** [comment]
Thank you! I think the group view needs some work. I think that "WICG: Digital Credentials API" should show up in the list of meetings for that group. Right now it appears to show up as its own meeting, with this error: No W3C group found for "WICG: Digital Credentials API”

**Comment by tidoust** [comment]
> Thank you! I think the group view needs some work. I think that "WICG: Digital Credentials API" should show up in the list of meetings for that group. Right now it appears to show up as its own meeting, with this error: No W3C group found for "WICG: Digital Credentials API”

Just to close the loop on this: that error should only appear when running an older version of the code. The new code lists group meetings with highlights in the list of meetings for that group.
