### ISSUE TITLE
For group meetings, do not touch minutes in calendar entries

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#145]
Group chairs should be able to edit the "minutes" portion of TPAC group calendar entries.

Notes on implementation:

* In calendar.mjs only manage minutes for breakouts.
* Validate.mjs looks ok
* Also check on add-minutes and minutes-to-w3c

**Comment by tidoust** [comment]
The code now preserves the information in "agenda" (text and URL), "description" and "minutes" fields. I note that the issue template used for TPAC 2024 meetings still has an "agenda" section. I think we did that as we didn't know how we would approach that issue. I don't suggest we drop the section at this stage (all issues would need to be updated otherwise). But I do propose we don't use the section :)

> * Also check on add-minutes and minutes-to-w3c

We cannot run these tools on group meetings. They assume that issues wil have a "Materials" section, and we're not planning to do that for group meetings.

**Comment by ianbjacobs** [comment]
Yay!
