### ISSUE TITLE
How can we record zoom information so that it is not publicly shared?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#17]
In theory, the best place is the calendar entry, but may raise issues.

**Comment by ianbjacobs** [comment]
Note: if zoom information is per-room, if we move a session from one room to another, it would be nice to update the zoom information.

Francois: we may be able to use settings for private data.

**Comment by tidoust** [comment]
Logic now looks for a `ROOM_ZOOM` environment variable to provide the mapping between room names and Zoom coordinates.

Note the solution changed. In the absence of endpoint, logic was created to drive the W3C calendar through Puppeteer, which allows running things in a GitHub job. Not ideal since this requires storing someone's credentials in a repo secret, but we'll make do with it.

The job sets the `ROOM_ZOOM` environment variable from a GitHub repo variable with the same name. A repo variable is visible to repo owners. That's totally fine for Zoom coordinates and this allows to update the mapping easily when needed.

What remains is documentation. Tracked in #27.
