### ISSUE TITLE
Any way to configure IRC bots based on channel data in GitHub?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#29]
Each session will have an IRC channel name (provided or generated). The morning of the meeting, can we automatically configure the bots on irc.w3.org based on this data?

**Comment by tidoust** [comment]
That should be doable through a local script. I'll look into it. Commands to run, on top of my head:

```
/join #my-super-channel
/invite RRSAgent
/invite Zakim
/topic Breakout: [meeting title] - [room] - [slot]
RRSAgent, make logs public [or "member" for restricted sessions]
Meeting: [meeting title]
Chair: [list of chairs]
Agenda: [agenda URL]
```

Anything else?
I don't think that we'll have to worry about "this meeting spans midnight" commands this year.

**Comment by tidoust** [comment]
Worth noting, bots will leave a channel after two hours of inactivity. RRSAgent can be told to stay. I don't think Zakim can (but then Zakim may not be that needed anymore).

**Comment by tidoust** [comment]
I created a CLI tool and related job to initialize IRC channels. Depending on parameters, the tool either runs the commands on the right IRC channels or return the commands for a user to run. The job should not be run more than one hour in advance, otherwise bots will just disappear from the channel.
